# FIXME: All tests CI should be run with the Release version.
# Continuous integration jobs
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs that consists of three steps:
  # 1) Installing the dependencies.
  # 2) Building the library.
  # 3) Running the tests.
  # These steps are repeated for both an Ubuntu and a MacOS virtual machine.
    build-Ubuntu:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Install Boost
          run: |
              sudo apt update
              sudo apt install -y libboost-all-dev
        - name: Install Eigen
          run: |
              sudo apt update
              sudo apt install libeigen3-dev
              sudo apt-get install -y lcov
        # Runs a single command using the runners shell
        - name: Build, run tests, and save coverage.
          shell: bash
          run: ./build-cov-gcc-ci.sh
        - run: bash <(curl -s https://codecov.io/bash) -f build/coverage.info || echo
    build-MacOS:
      # The type of runner that the job will run on
      runs-on: macos-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Install Homebrew
          run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        - name: Install Boost
          run: brew install boost
        - name: Install Eigen
          run: brew install eigen
        # Runs a single command using the runners shell
        - name: Build
          shell: bash
          run: |
            mkdir -p build && cd build
            cmake ..
            make
        # Runs a set of commands using the runners shell
        - name: Run Tests
          run: |
            cd build/tests/
            ./RunTests

    build-Windows:
      # The type of runner that the job will run on
      runs-on: windows-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Install Boost
          run: choco install boost-msvc-14.2
        - name: Install Eigen
          run: choco install eigen
        # Runs a single command using the runners shell
        - name: Build
          shell: bash
          run: |
            mkdir -p build && cd build
            cmake ..
            cmake --build .
        # Runs a set of commands using the runners shell
        - name: Run Tests
          run: |
            cd build/tests/Debug
            ./RunTests
